version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_PORT=${NODE_PORT}
      - NODE_ENV=development
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    # Volumes to mount
    volumes:
      - ./server/src:/app/server/src
    restart: always
#
#  ##########################
#  ### SETUP CLIENT CONTAINER
#  ##########################
#  react:
#    build: ./client
#    ports:
#      - 8000:8000
#    links:
#      - node
#    restart: always
